### ISSUE TITLE
change pin's icon

### ISSUE THREAD

**Issue by omidn** [s1na/sc2map#11]
Each of the pins on the map, showing a point in the map are visualized with a default marker. We should get a icon pack of factories and use a more relevant and specific picture for each point.

**Comment by s1na** [comment]
We probably need different type of nodes, such as plants, factories and warehouses. However I don't know which types are necessary.
At the moment, every node is shown as factory.

**Comment by omidn** [comment]
yeah, maybe these?
http://www.freepik.com/free-vector/factories-and-industry-icons_753561.htm#term=factory&page=1&position=0

**Comment by acid0078** [comment]
think its ok for now
